source("get_some_data.R")
source("draw_a_chart_of_cumulative_cases.R")
source("draw_a_chart_of_cumulative_deaths.R")
source("draw_a_chart_of_new_cases_in_last_week.R")
source("draw_a_chart_of_new_deaths_in_last_week.R")
